### ISSUE TITLE
ErrorMetaConfig not declared by package gpc

### ISSUE THREAD

**Issue by rizqirenaldy27** [restuwahyu13/go-playground-converter#2]
ada error ErrorMetaConfig not declared by package gpc di validator.go kita saya mau coba d repo gitlab
<img width="1221" alt="Screenshot 2022-11-16 at 10 46 17" src="https://user-images.githubusercontent.com/21188924/202078780-0364835f-dd71-4291-a5f8-9f13f5455f57.png">

**Comment by restuwahyu13** [comment]
@rizqirenaldy27 untuk versi terbaru sudah tidak menggunakan `ErrorMetaConfig`, `NewValidator`, `NewBindingValidator` lagi, silah cek dokumentasi untuk penggunaan terbaru terkait **go-playground-validator**. terimakasih
